eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/

server:
  port: 8764
spring:
  application:
    name: service-hi
