server:
  port: 8002

spring:
  application:
    name: eureka-serve

eureka:
  instance:
    hostname: replica1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://replica1:8001/eureka/

